### ISSUE TITLE
installed but not working on splunk cloud.  

### ISSUE THREAD

**Issue by kundeng** [nadavc2c/TA-ob-openai-chatgpt#1]
04-05-2024 14:05:54.432 INFO  SearchPhaseGenerator [3580172 searchOrchestrator] -  Executing two phase fallback for the search=|makeresults 1| eval prompt="what can you say about splunk?" | obopenai prompt=prompt mode="nadav"
04-05-2024 14:05:54.432 INFO  SearchParser [3580172 searchOrchestrator] - PARSING: |makeresults 1| eval prompt="what can you say about splunk?" | obopenai prompt=prompt mode="nadav"
04-05-2024 14:05:54.433 INFO  ServerConfig [3580172 searchOrchestrator] - Will add app jailing prefix /opt/splunk/bin/nsjail-wrapper for TA-ob-openai-chatgpt
04-05-2024 14:05:54.433 INFO  ChunkedExternProcessor [3580172 searchOrchestrator] - Running process: /opt/splunk/bin/nsjail-wrapper /opt/splunk/bin/python2.7 /opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py
04-05-2024 14:05:54.526 ERROR ChunkedExternProcessor [3580188 ChunkedExternProcessorStderrLogger] - stderr: Traceback (most recent call last):
04-05-2024 14:05:54.526 ERROR ChunkedExternProcessor [3580188 ChunkedExternProcessorStderrLogger] - stderr:   File "/opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py", line 10, in <module>
04-05-2024 14:05:54.526 ERROR ChunkedExternProcessor [3580188 ChunkedExternProcessorStderrLogger] - stderr:     from urllib.parse import urlparse
04-05-2024 14:05:54.526 ERROR ChunkedExternProcessor [3580188 ChunkedExternProcessorStderrLogger] - stderr: ImportError: No module named parse
04-05-2024 14:05:54.531 ERROR ChunkedExternProcessor [3580172 searchOrchestrator] - EOF while attempting to read transport header read_size=0
04-05-2024 14:05:54.531 ERROR ChunkedExternProcessor [3580172 searchOrchestrator] - Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.532 ERROR SearchPhaseGenerator [3580172 searchOrchestrator] - Fallback to two phase failed with SearchProcessorException: Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.532 WARN  SearchPhaseGenerator [3580172 searchOrchestrator] - Failed to create search phases: exception=31SearchProcessorMessageException, error=Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.537 INFO  SearchStatusEnforcer [3580172 searchOrchestrator] - sid=1712325954.992175, newState=BAD_INPUT_CANCEL, message=Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.537 ERROR SearchStatusEnforcer [3580172 searchOrchestrator] - SearchMessage orig_component=ChunkedExternProcessor sid=1712325954.992175 message_key=CHUNKED:NON_ZERO_EXIT__%d message=Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.537 INFO  SearchStatusEnforcer [3580172 searchOrchestrator] - State changed to BAD_INPUT_CANCEL: Error in 'obopenai' command: External search command exited unexpectedly with non-zero error code 1.
04-05-2024 14:05:54.550 INFO  SearchStatusEnforcer [3580172 searchOrchestrator] - Enforcing disk quota = 52428800000
04-05-2024 14:05:54.563 INFO  DispatchManager [3580172 searchOrchestrator] - DispatchManager::dispatchHasFinished(id='1712325954.992175', username='kundeng')
04-05-2024 14:05:54.563 INFO  UserManager [3580172 searchOrchestrator] - Unwound user context: kundeng -> NULL
04-05-2024 14:05:54.563 INFO  SearchOrchestrator [3580169 RunDispatch] - SearchOrchestrator is destructed.  sid=1712325954.992175, eval_only=0
04-05-2024 14:05:54.563 INFO  SearchStatusEnforcer [3580169 RunDispatch] - SearchStatusEnforcer is already terminated
04-05-2024 14:05:54.563 INFO  UserManager [3580169 RunDispatch] - Unwound user context: kundeng -> NULL
04-05-2024 14:05:54.563 INFO  LookupDataProvider [3580169 RunDispatch] - Clearing out lookup shared provider map
04-05-2024 14:05:54.564 INFO  dispatchRunner [162941 MainThread] - RunDispatch is done: sid=1712325954.992175, exit=0

**Comment by kundeng** [comment]
tried python.version=python3 in commands.conf, but got error message.  
Then tried 
```
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
 ```
Still doesn't work.

**Comment by kundeng** [comment]
04-05-2024 16:29:59.014 INFO  ChunkedExternProcessor [3373950 searchOrchestrator] - Running process: /opt/splunk/bin/nsjail-wrapper /opt/splunk/bin/python2.7 /opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: Traceback (most recent call last):
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr:   File "/opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py", line 19, in <module>
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr:     import openai
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr:   File "/opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/../lib/openai/__init__.py", line 46
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr:     api_key_path: Optional[str] = os.environ.get("OPENAI_API_KEY_PATH")
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr:                 ^
04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: SyntaxError: invalid syntax



Seems that I need to force it to run as python3, but unable to

**Comment by nadavc2c** [comment]
> 04-05-2024 16:29:59.014 INFO ChunkedExternProcessor [3373950 searchOrchestrator] - Running process: /opt/splunk/bin/nsjail-wrapper /opt/splunk/bin/python2.7 /opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: Traceback (most recent call last): 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: File "/opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/obopenai.py", line 19, in 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: import openai 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: File "/opt/splunk/etc/apps/TA-ob-openai-chatgpt/bin/../lib/openai/**init**.py", line 46 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: api_key_path: Optional[str] = os.environ.get("OPENAI_API_KEY_PATH") 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: ^ 04-05-2024 16:29:59.159 ERROR ChunkedExternProcessor [3373974 ChunkedExternProcessorStderrLogger] - stderr: SyntaxError: invalid syntax
> 
> Seems that I need to force it to run as python3, but unable to

Hi,
how did you install it in Splunk Cloud?
I see in that the app is still pending to be available in the cloud. Here https://splunkbase.splunk.com/app/6957 it does not specify compatibility to Cloud so it's not downloadable from the cloud Splunkbase.
As far as I know, Python 2 was removes from Splunk cloud, what version and build are you using? (in Splunk cloud, go to [Support & Services] on the upper right, then [About])
Thanks

**Comment by kundeng** [comment]
I just downloaded from the above URL and then installed it directly using splunk cloud web UI as a private app.

**Comment by kundeng** [comment]
I am not sure why python 2 is still being used for our tenant.  We have 9.12 Victoria.

**Comment by nadavc2c** [comment]
I uploaded a new version that is now pending for Victoria with `python.version = python3`, I hope it will help. Anyways maybe Splunk support know why python 2 exists in your environment, because I think it should have been deleted completely.

**Comment by kundeng** [comment]
I talked to splunk support, they have been playing ball and refusing to remove python 2.  Anyway,  did you put that in app.conf, as I tried to put it into commands.conf and it didn't work.  They told me that python3 needs to be specified in app.conf.

**Comment by nadavc2c** [comment]
I didn't put it in app.conf because according to the docs it should use "Default: the system-wide Python version". The new version is stuck pending for cloud, I tried to create a new [app](https://github.com/nadavc2c/TA-ob-openai-chatgpt) but it is still pending. you can try to add this setting to app.conf, but I think that if python2 is your system-wide Python version it can be a security risk so it might be worth to escalate this issue with their support. I hope they will help
