### ISSUE TITLE
indentation wrong?  

### ISSUE THREAD

**Issue by kundeng** [nadavc2c/TA-ob-openai-chatgpt#3]
'''
    def _set_conf_settings(self):
        # get collection
        obopenai_settings_conf = self.service.confs[custom_conf_file]["additional_parameters"]

        try:
            if obopenai_settings_conf["api_base"]:
                url_parse = urlparse(obopenai_settings_conf["api_base"])
                if url_parse.scheme == "https":
                    openai.api_base = obopenai_settings_conf["api_base"]
                elif url_parse.scheme == '':
                    url_partition = obopenai_settings_conf["api_base"].partition("//")
                    if sha256(url_partition[0].encode()).hexdigest() == \
                            '197946480c751003199f56c25fa6ef2117f4f34f49e1b63f82bfba74934fcc27':
                        openai.api_base = url_partition[2]
                    else:
                        raise ValueError("Error: URL must start with https://")
                else:
                    raise ValueError("Error: URL must start with https://")
        except AttributeError or KeyError:
            pass

            openai.organization = obopenai_settings_conf["organization_id"]

        openai.api_key = self._get_decrypted_password()
   '''

the line with openai.organization is wrongly placed or indented.

**Comment by nadavc2c** [comment]
It will be fixed in the next version, thanks
