### ISSUE TITLE
collections.conf without fields causes lookup to fail. 

### ISSUE THREAD

**Issue by kundeng** [nadavc2c/TA-ob-openai-chatgpt#4]
On splunk 9.x,  I had to add the <field>=<type> in there.

**Comment by nadavc2c** [comment]
according to the docs https://dev.splunk.com/enterprise/docs/developapps/manageknowledge/kvstore/usingconfigurationfiles/#Examples , all you need to create a KV Store collection is the stanza name. can you upload screenshots of what you experience?

**Comment by nadavc2c** [comment]
anyway I added field restrictions
